export const userInitialStateData = {
  age: 0,
  email: "",
  biological_sex: "",
  height: 0,
  weight: 0,
};

export const todaysInitialStateData = {
  date: "",
  bedtimeStart: "",
  bedtimeEnd: "",
  data: {
    readiness: {
      contributors: {
        activity_balance: 0,
        body_temperature: 0,
        hrv_balance: 0,
        previous_day_activity: 0,
        previous_night: 0,
        recovery_index: 0,
        resting_heart_rate: 0,
        sleep_balance: 0,
      },
      day: "",
      score: 0,
      temperature_deviation: 0,
      temperature_trend_deviation: 0,
      timestamp: "",
    },
    dailySleep: {
      contributors: {
        deep_sleep: 0,
        efficiency: 0,
        latency: 0,
        rem_sleep: 0,
        restfulness: 0,
        timing: 0,
        total_sleep: 0,
      },
      day: "",
      score: 0,
      timestamp: "",
    },
    activity: {
      class_5_min: "string",
      score: 0,
      active_calories: 0,
      average_met_minutes: 0,
      contributors: {
        meet_daily_targets: 0,
        move_every_hour: 0,
        recovery_time: 0,
        stay_active: 0,
        training_frequency: 0,
        training_volume: 0,
      },
      equivalent_walking_distance: 0,
      high_activity_met_minutes: 0,
      high_activity_time: 0,
      inactivity_alerts: 0,
      low_activity_met_minutes: 0,
      low_activity_time: 0,
      medium_activity_met_minutes: 0,
      medium_activity_time: 0,
      met: {
        interval: 0,
        items: [],
        timestamp: "string",
      },
      meters_to_target: 0,
      non_wear_time: 0,
      resting_time: 0,
      sedentary_met_minutes: 0,
      sedentary_time: 0,
      steps: 0,
      target_calories: 0,
      target_meters: 0,
      total_calories: 0,
      day: "string",
      timestamp: "string",
    },
    heartRate: {
      day: "",
      heartRateData: [],
    },
    tags: {
      day: "",
      tagData: [],
    },
    sessions: {
      day: "",
      sessionData: [],
    },
    sleepPeriod: {
      average_breath: 0,
      average_heart_rate: 0,
      average_hrv: 0,
      awake_time: 0,
      bedtime_end: "string",
      bedtime_start: "string",
      day: "string",
      deep_sleep_duration: 0,
      efficiency: 0,
      heart_rate: {
        interval: 0,
        items: [],
        timestamp: "string",
      },
      hrv: {
        interval: 0,
        items: [],
        timestamp: "string",
      },
      latency: 0,
      light_sleep_duration: 0,
      low_battery_alert: false,
      lowest_heart_rate: 0,
      movement_30_sec: "string",
      period: 0,
      readiness_score_delta: 0,
      rem_sleep_duration: 0,
      restless_periods: 0,
      sleep_phase_5_min: "string",
      sleep_score_delta: 0,
      time_in_bed: 0,
      total_sleep_duration: 0,
      type: "string",
    },
    workouts: {
      day: "",
      workoutData: [],
    },
  },
};

export const globalContextInitialState = {
  userData: userInitialStateData,
  readinessData: [],
  dailySleepData: [],
  activityData: [],
  mergedHeartRateData: [],
  mergedTagData: [],
  mergedSessionData: [],
  sleepPeriodData: [],
  mergedWorkoutData: [],
  startDate: "",
  setStartDate: () => "",
  endDate: "",
  setEndDate: () => "",
  todaysData: todaysInitialStateData,
  setTodaysData: () => {},
  isMobileDisplay: false,
  setIsMobileDisplay: () => false,
  btnOffsetLeft: 0,
  setBtnOffsetLeft: () => 0,
  isBtnPosition: true,
  setIsBtnPosition: () => true,
};
